# Generated by Django 3.2.16 on 2023-05-29 10:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('stadium', models.CharField(max_length=256, verbose_name='stadium')),
                ('cover_image', models.ImageField(upload_to='facility/', verbose_name='cover name')),
                ('longitude', models.FloatField(verbose_name='location - longitude')),
                ('latitude', models.FloatField(verbose_name='location - latitude')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
