# Generated by Django 3.2.16 on 2023-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.BigIntegerField(verbose_name='facility_id')),
                ('court_type', models.CharField(choices=[('FULL', 'Full'), ('HALF', 'Half'), ('QUARTER', 'Quarter')], default='FULL', max_length=255)),
                ('day_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('WEEKEND', 'Weekend')], default='WEEKDAY', max_length=255)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('full_day_price', models.PositiveIntegerField()),
                ('low_time_price', models.PositiveIntegerField()),
                ('high_time_price', models.PositiveIntegerField()),
                ('separation_timing', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='SKU',
        ),
    ]
