# Generated by Django 3.2.16 on 2023-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230531_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.BigIntegerField(verbose_name='facility_id')),
                ('date', models.DateField(verbose_name='date')),
                ('court_type', models.CharField(choices=[('FULL', 'Full'), ('HALF', 'Half'), ('QUARTER', 'Quarter')], default='FULL', max_length=255)),
                ('is_lock', models.BooleanField(default=False)),
                ('is_order', models.BooleanField(default=False)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.BigIntegerField(verbose_name='facility_id')),
                ('date', models.DateField(verbose_name='date')),
                ('slot', models.CharField(max_length=255, verbose_name='slot')),
            ],
        ),
    ]
