# Generated by Django 3.2.16 on 2023-06-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_freeze_court_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='location',
            field=models.CharField(blank=True, max_length=1024, verbose_name='location'),
        ),
    ]
