# Generated by Django 3.2.16 on 2023-06-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_facility_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('longitude', models.FloatField(verbose_name='location - longitude')),
                ('latitude', models.FloatField(verbose_name='location - latitude')),
                ('location', models.CharField(blank=True, max_length=1024, verbose_name='location')),
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='stadium',
        ),
    ]
