# Generated by Django 3.2.16 on 2023-06-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_facility_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='cover_image',
        ),
        migrations.CreateModel(
            name='FacilityCoverImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility/')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.facility')),
            ],
        ),
    ]
