# Generated by Django 3.2.16 on 2023-06-06 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_lockinfo_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockinfo',
            name='date',
        ),
        migrations.AddField(
            model_name='freeze',
            name='lock_count',
            field=models.IntegerField(default=0, verbose_name='lock_count'),
        ),
        migrations.AddField(
            model_name='lockinfo',
            name='from_date',
            field=models.DateField(default=datetime.date.today, verbose_name='from_date'),
        ),
        migrations.AddField(
            model_name='lockinfo',
            name='to_date',
            field=models.DateField(default=datetime.date.today, verbose_name='to_date'),
        ),
    ]
