# Generated by Django 3.2.16 on 2023-06-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230606_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
