# Generated by Django 3.2.16 on 2023-06-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_stadium_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockinfo',
            name='lock_type',
            field=models.CharField(choices=[('REPEAT', 'Repeat'), ('CONTINUOUS', 'Continuous')], default='REPEAT', max_length=255, verbose_name='lock_type'),
        ),
    ]
