# Generated by Django 3.2.16 on 2023-06-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_lockinfo_lock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitycoverimage',
            name='image',
        ),
        migrations.AddField(
            model_name='facilitycoverimage',
            name='file_id',
            field=models.CharField(default='', max_length=2048, verbose_name='file_id'),
        ),
        migrations.AddField(
            model_name='facilitycoverimage',
            name='file_path',
            field=models.CharField(default='', max_length=2048, verbose_name='file_path'),
        ),
    ]
