# Generated by Django 3.2.16 on 2023-06-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20230609_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='full_day_price',
            field=models.FloatField(null=True),
        ),
    ]
