# Generated by Django 3.2.16 on 2023-06-16 07:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_price_full_day_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='full_day_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
    ]
