# Generated by Django 3.2.16 on 2023-06-21 09:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='order_id')),
                ('trade_no', models.CharField(max_length=1024)),
                ('bill_type', models.CharField(choices=[('Payment', 'Payment'), ('Refund', 'Refund')], default='Payment', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('transaction_id', models.CharField(max_length=1024, null=True)),
                ('nonce_str', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.BigIntegerField(verbose_name='facility_id')),
                ('user_id', models.BigIntegerField(verbose_name='user_id')),
                ('status', models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Pending Confirmation', 'Pending Confirmation'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending Payment', max_length=255)),
                ('date', models.DateField(verbose_name='date')),
                ('court_type', models.CharField(choices=[('FULL', 'Full'), ('HALF', 'Half'), ('QUARTER', 'Quarter')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=2048, null=True)),
                ('time_list', models.CharField(max_length=2048)),
            ],
        ),
        migrations.RemoveField(
            model_name='freeze',
            name='court_type',
        ),
        migrations.AddField(
            model_name='freeze',
            name='weights',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
    ]
