# Generated by Django 3.2.16 on 2023-06-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20230621_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='tbd', max_length=64, verbose_name='order_no'),
            preserve_default=False,
        ),
    ]
