# Generated by Django 3.2.16 on 2023-06-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_full_day',
            field=models.BooleanField(default=False),
        ),
    ]
