# Generated by Django 3.2.16 on 2023-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_order_is_full_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=32, verbose_name='phone_number'),
        ),
    ]
