# Generated by Django 3.2.16 on 2023-07-11 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, null=True),
        ),
    ]
