# Generated by Django 3.2.16 on 2023-07-17 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_bill_refunded_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='StadiumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(default='', max_length=2048, verbose_name='file_path')),
                ('file_id', models.CharField(default='', max_length=2048, verbose_name='file_id')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.stadium')),
            ],
        ),
    ]
