# Generated by Django 3.2.16 on 2023-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20230808_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpaidOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='order_id')),
            ],
        ),
    ]
