version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_booking-system-service
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=booking-system-service
      - role=container
    environment:
      - DB_ENGINE=mysql
      - DB_NAME=booking
      - DB_USERNAME=root
      - DB_PASSWORD=book123@
      - DB_HOST=10.18.111.68
      - DB_PORT=3306
networks:
  default:
    external:
      name: wxcb0
