version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_booking-system-service
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=booking-system-service
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=book123@
      - MYSQL_ADDRESS=10.18.111.68:3306
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
networks:
  default:
    external:
      name: wxcb0
