# Generated by Django 3.2.16 on 2023-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='', max_length=255, verbose_name='nick_name'),
        ),
    ]
